"""esquema inicial

Revision ID: 4426779e3621
Revises: 
Create Date: 2026-08-19 16:45:34.636246
"""
from alembic import op
import sqlalchemy as sa


revision = '4426779e3621'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('folio', sa.String(length=32), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index('ix_activity_created', ['created_at'], unique=False)

    op.create_table('credential',
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('must_change', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=32), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('authorization', sa.String(length=64), nullable=True),
    sa.Column('customer_name', sa.String(length=160), nullable=True),
    sa.Column('customer_email', sa.String(length=160), nullable=True),
    sa.Column('customer_phone', sa.String(length=64), nullable=True),
    sa.Column('customer_city', sa.String(length=120), nullable=True),
    sa.Column('vehicle_title', sa.String(length=200), nullable=True),
    sa.Column('vehicle_location', sa.String(length=120), nullable=True),
    sa.Column('vehicle_vin', sa.String(length=17), nullable=True),
    sa.Column('vehicle_year', sa.String(length=8), nullable=True),
    sa.Column('vehicle_type', sa.String(length=64), nullable=True),
    sa.Column('vehicle_mileage', sa.String(length=32), nullable=True),
    sa.Column('vehicle_fuel', sa.String(length=32), nullable=True),
    sa.Column('vehicle_transmission', sa.String(length=32), nullable=True),
    sa.Column('vehicle_carfax', sa.String(length=64), nullable=True),
    sa.Column('pricing_vehicle_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('pricing_reservation_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('pricing_discount', sa.String(length=120), nullable=True),
    sa.Column('pricing_coverage', sa.String(length=120), nullable=True),
    sa.Column('pricing_transport', sa.String(length=120), nullable=True),
    sa.Column('pricing_currency', sa.String(length=8), nullable=True),
    sa.Column('banking_bank', sa.String(length=120), nullable=True),
    sa.Column('banking_beneficiary', sa.String(length=160), nullable=True),
    sa.Column('banking_account_label', sa.String(length=64), nullable=True),
    sa.Column('banking_account_number', sa.String(length=40), nullable=True),
    sa.Column('banking_bank_account', sa.String(length=40), nullable=True),
    sa.Column('banking_payment_reference', sa.String(length=64), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('delivery_mode', sa.String(length=32), nullable=True),
    sa.Column('delivery_text', sa.Text(), nullable=True),
    sa.Column('delivery_alt', sa.Text(), nullable=True),
    sa.Column('representative_name', sa.String(length=120), nullable=True),
    sa.Column('representative_role', sa.String(length=120), nullable=True),
    sa.Column('representative_phone', sa.String(length=64), nullable=True),
    sa.Column('representative_email', sa.String(length=160), nullable=True),
    sa.Column('representative_hours', sa.String(length=160), nullable=True),
    sa.Column('verify_url_base', sa.String(length=200), nullable=True),
    sa.Column('duplicated_from_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['duplicated_from_id'], ['invoice.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index('ix_invoice_locale', ['locale'], unique=False)
        batch_op.create_index('ix_invoice_status', ['status'], unique=False)
        batch_op.create_index('ix_invoice_vin', ['vehicle_vin'], unique=False)

    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'market', name='uq_setting_key_market')
    )
    op.create_table('invoice_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'position', name='uq_photo_invoice_pos')
    )
    op.create_table('invoice_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=32), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('pdf_path', sa.String(length=255), nullable=True),
    sa.Column('html_path', sa.String(length=255), nullable=True),
    sa.Column('assets_dir', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'version', name='uq_snapshot_invoice_ver')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_snapshot')
    op.drop_table('invoice_photo')
    op.drop_table('setting')
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index('ix_invoice_vin')
        batch_op.drop_index('ix_invoice_status')
        batch_op.drop_index('ix_invoice_locale')

    op.drop_table('invoice')
    op.drop_table('credential')
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_created')

    op.drop_table('activity_log')
    # ### end Alembic commands ###
